FROM ubuntu
RUN apt-get update -y
RUN apt-get install -y apache2
RUN apt-get install -y apache2-utils
EXPOSE 80
ENTRYPOINT ["apache2ctl"]
CMD ["-DFOREGROUND"]
===========================================
FROM ubuntu
MAINTAINER anoohhya <anoohhya@gmail.com>
RUN apt-get update && apt-get install -y mysql-server
RUN apt-get install -y mysql-client-core-8.0
ENV MYSQL_ROOT_PASSWORD 123
EXPOSE 9080